# Generated by Django 5.2.10 on 2026-01-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dataset name/filename', max_length=255)),
                ('file', models.FileField(help_text='Uploaded CSV file', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0, help_text='Number of equipment records')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0.0)),
                ('avg_pressure', models.FloatField(default=0.0)),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('min_flowrate', models.FloatField(default=0.0)),
                ('max_flowrate', models.FloatField(default=0.0)),
                ('min_pressure', models.FloatField(default=0.0)),
                ('max_pressure', models.FloatField(default=0.0)),
                ('min_temperature', models.FloatField(default=0.0)),
                ('max_temperature', models.FloatField(default=0.0)),
                ('std_flowrate', models.FloatField(default=0.0)),
                ('std_pressure', models.FloatField(default=0.0)),
                ('std_temperature', models.FloatField(default=0.0)),
                ('type_distribution', models.JSONField(default=dict, help_text='Distribution of equipment types')),
                ('stats_by_type', models.JSONField(default=dict, help_text='Detailed statistics grouped by equipment type')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(help_text='Related dataset', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='equipment.dataset')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Equipment name/identifier', max_length=255)),
                ('type', models.CharField(help_text='Equipment type/category', max_length=100)),
                ('flowrate', models.FloatField(help_text='Flow rate measurement')),
                ('pressure', models.FloatField(help_text='Pressure measurement')),
                ('temperature', models.FloatField(help_text='Temperature measurement')),
                ('dataset', models.ForeignKey(help_text='Parent dataset', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='equipment.dataset')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
